### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by AbleTheAbove** [azur1s/gomi#1]
Working on this project would be hard as there is no documentation

I'd highly recommend working on documenting code so I may work on this project more easily

**Comment by azur1s** [comment]
working on it

**Comment by azur1s** [comment]
I added [comments](5aeb4a6dcca255cef7a85a486dcf103645a667ec) and separated stuff into their own files, is it more readable now?

**Comment by AbleTheAbove** [comment]
Much more readable!

**Comment by azur1s** [comment]
glad you liked it!
